heat_template_version: 2015-04-30
resources:
  private_network:
    type: OS::Neutron::Net
    properties:
      name: private_net

  private_subnet:
    type: OS::Neutron::Subnet
    properties:
      network: {get_resource: private_network}
      name: private_subnet
      cidr: 172.20.0.0/20
      dns_nameservers: [ "8.8.8.8", "8.8.4.4" ]
      enable_dhcp: true

  private_router:
    type: OS::Neutron::Router
    properties:
      name: private_router
      external_gateway_info: { network: public }

  private_router_i1:
    type: OS::Neutron::RouterInterface
    properties:
      router: {get_resource: private_router}
      subnet: {get_resource: private_subnet}

  min_sg:
    type: OS::Neutron::SecurityGroup
    properties:
      name: min_sg
      description: Ping and SSH
      rules:
      - protocol: icmp
        port_range_min: 8
      - protocol: tcp
        port_range_min: 22
        port_range_max: 22

  bmc_sg:
    type: OS::Neutron::SecurityGroup
    properties:
      name: bmc_sg
      description: Ping, SSH and ipmi
      rules:
      - protocol: icmp
        port_range_min: 8
      - protocol: tcp
        port_range_min: 22
        port_range_max: 22
      - protocol: udp
        port_range_min: 623
        port_range_max: 623

  all_sg:
    type: OS::Neutron::SecurityGroup
    properties:
      name: all_sg
      description: Allows all traffic
      rules: 
      - protocol: icmp
      - protocol: tcp
      - protocol: udp

  testenv_key:
    type: OS::Nova::KeyPair
    properties:
      name: testenv_key
      public_key: {get_file: test_env_id_rsa.pub}
